use canvas;

LOAD DATA LOCAL INFILE 'student.csv' INTO TABLE student
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'class.csv' INTO TABLE class
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'takes.csv' INTO TABLE takes
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'assignment.csv' INTO TABLE assignment
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ass_grade.csv' INTO TABLE ass_grade
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'qa2.csv' INTO TABLE qa
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'threads.csv' INTO TABLE threads
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'teaches.csv' INTO TABLE teaches
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ta.csv' INTO TABLE ta
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'post_tag.csv' INTO TABLE post_tag
FIELDS TERMINATED BY ',' IGNORE 1 LINES;
